/**
 * dict[0]: 대분류
 * dict[1]: 중분류
 * dict[2]: 클래스
 */

export default {
  a3: ['cc', 'Chief Complaint'],
  a4: ['cc', 'Chief Complaint'],
  a5: ['cc', 'Chief Complaint'],
  a6: ['cc', 'Chief Complaint'],
  a7: ['cc', 'Chief Complaint'],
  a8: ['cc', 'Chief Complaint'],
  a9: ['cc', 'Chief Complaint'],
  b3: ['pi', 'Location'],
  b4: ['pi', 'Location'],
  b5: ['pi', 'Location'],
  b6: ['pi', 'Location'],
  b7: ['pi', 'Location'],
  b8: ['pi', 'Location'],
  b9: ['pi', 'Location'],
  b10: ['pi', 'Location'],
  b11: ['pi', 'Location'],
  b12: ['pi', 'Location'],
  b13: ['pi', 'Location'],
  d3: ['pi', 'Character'],
  d5: ['pi', 'Character'],
  d6: ['pi', 'Character'],
  d7: ['pi', 'Character'],
  d8: ['pi', 'Character'],
  d9: ['pi', 'Character'],
  d10: ['pi', 'Character'],
  d11: ['pi', 'Character'],
  d12: ['pi', 'Character'],
  d13: ['pi', 'Character'],
  d14: ['pi', 'Character'],
  d15: ['pi', 'Character'],
  d16: ['pi', 'Character'],
  d17: ['pi', 'Character'],
  d18: ['pi', 'Character'],
  d19: ['pi', 'Character'],
  d20: ['pi', 'Character'],
  d21: ['pi', 'Character'],
  d22: ['pi', 'Character'],
  d23: ['pi', 'Character'],
  d24: ['pi', 'Character'],
  d25: ['pi', 'Character'],
  d26: ['pi', 'Character'],
  d27: ['pi', 'Character'],
  d28: ['pi', 'Character'],
  d29: ['pi', 'Character'],
  d30: ['pi', 'Character'],
  d31: ['pi', 'Character'],
  d32: ['pi', 'Character'],
  d33: ['pi', 'Character'],
  d34: ['pi', 'Character'],
  d35: ['pi', 'Character'],
  d37: ['pi', 'Character'],
  d38: ['pi', 'Character'],
  d39: ['pi', 'Character'],
  d41: ['pi', 'Character'],
  d42: ['pi', 'Character'],
  d43: ['pi', 'Character'],
  d44: ['pi', 'Character'],
  d46: ['pi', 'Character'],
  e3: ['pi', 'Factors'],
  e4: ['pi', 'Factors'],
  e5: ['pi', 'Factors'],
  e6: ['pi', 'Factors'],
  e7: ['pi', 'Factors'],
  e8: ['pi', 'Factors'],
  e9: ['pi', 'Factors'],
  e10: ['pi', 'Factors'],
  e11: ['pi', 'Factors'],
  e12: ['pi', 'Factors'],
  e13: ['pi', 'Factors'],
  e14: ['pi', 'Factors'],
  e15: ['pi', 'Factors'],
  e16: ['pi', 'Factors'],
  e17: ['pi', 'Factors'],
  e18: ['pi', 'Factors'],
  e19: ['pi', 'Factors'],
  e20: ['pi', 'Factors'],
  e21: ['pi', 'Factors'],
  e22: ['pi', 'Factors'],
  e23: ['pi', 'Factors'],
  e24: ['pi', 'Factors'],
  e25: ['pi', 'Factors'],
  e26: ['pi', 'Factors'],
  e27: ['pi', 'Factors'],
  e28: ['pi', 'Factors'],
  f3: ['ros', 'Associated Symptoms'],
  f4: ['ros', 'Associated Symptoms'],
  f5: ['ros', 'Associated Symptoms'],
  f6: ['ros', 'Associated Symptoms'],
  f7: ['ros', 'Associated Symptoms'],
  f8: ['ros', 'Associated Symptoms'],
  f9: ['ros', 'Associated Symptoms'],
  f10: ['ros', 'Associated Symptoms'],
  f11: ['ros', 'Associated Symptoms'],
  f12: ['ros', 'Associated Symptoms'],
  f13: ['ros', 'Associated Symptoms'],
  f14: ['ros', 'Associated Symptoms'],
  f15: ['ros', 'Associated Symptoms'],
  f16: ['ros', 'Associated Symptoms'],
  f17: ['ros', 'Associated Symptoms'],
  f18: ['ros', 'Associated Symptoms'],
  f19: ['ros', 'Associated Symptoms'],
  f20: ['ros', 'Associated Symptoms'],
  f21: ['ros', 'Associated Symptoms'],
  f22: ['ros', 'Associated Symptoms'],
  f23: ['ros', 'Associated Symptoms'],
  f24: ['ros', 'Associated Symptoms'],
  f25: ['ros', 'Associated Symptoms'],
  f26: ['ros', 'Associated Symptoms'],
  f27: ['ros', 'Associated Symptoms'],
  f28: ['ros', 'Associated Symptoms'],
  f29: ['ros', 'Associated Symptoms'],
  f30: ['ros', 'Associated Symptoms'],
  f31: ['ros', 'Associated Symptoms'],
  f32: ['ros', 'Associated Symptoms'],
  f33: ['ros', 'Associated Symptoms'],
  f34: ['ros', 'Associated Symptoms'],
  f35: ['ros', 'Associated Symptoms'],
  f36: ['ros', 'Associated Symptoms'],
  f37: ['ros', 'Associated Symptoms'],
  f38: ['ros', 'Associated Symptoms'],
  f39: ['ros', 'Associated Symptoms'],
  f40: ['ros', 'Associated Symptoms'],
  f41: ['ros', 'Associated Symptoms'],
  f42: ['ros', 'Associated Symptoms'],
  f43: ['ros', 'Associated Symptoms'],
  f44: ['ros', 'Associated Symptoms'],
  f45: ['ros', 'Associated Symptoms'],
  f46: ['ros', 'Associated Symptoms'],
  f47: ['ros', 'Associated Symptoms'],
  f48: ['ros', 'Associated Symptoms'],
  f49: ['ros', 'Associated Symptoms'],
  f50: ['ros', 'Associated Symptoms'],
  f51: ['ros', 'Associated Symptoms'],
  f52: ['ros', 'Associated Symptoms'],
  f53: ['ros', 'Associated Symptoms'],
  f54: ['ros', 'Associated Symptoms'],
  f55: ['ros', 'Associated Symptoms'],
  f56: ['ros', 'Associated Symptoms'],
  f57: ['ros', 'Associated Symptoms'],
  f58: ['ros', 'Associated Symptoms'],
  f59: ['ros', 'Associated Symptoms'],
  f60: ['ros', 'Associated Symptoms'],
  g3: ['pi', 'Course'],
  g8: ['pi', 'Course'],
  h3: ['pi', 'Course'],
  h6: ['pi', 'Course'],
  h8: ['pi', 'Course'],
  j3: ['pmh', 'Experience'],
  j4: ['pmh', 'Experience'],
  j5: ['pmh', 'Experience'],
  j6: ['pmh', 'Experience'],
  j7: ['pmh', 'Experience'],
  j8: ['pmh', 'Experience'],
  j9: ['pmh', 'Experience'],
  j10: ['pmh', 'Experience'],
  j11: ['pmh', 'Experience'],
  j12: ['pmh', 'Experience'],
  j13: ['pmh', 'Experience'],
  j14: ['pmh', 'Experience'],
  j15: ['pmh', 'Experience'],
  j16: ['pmh', 'Experience'],
  j17: ['pmh', 'Experience'],
  j18: ['pmh', 'Experience'],
  j19: ['pmh', 'Experience'],
  j20: ['pmh', 'Experience'],
  j21: ['pmh', 'Experience'],
  j22: ['pmh', 'Experience'],
  j23: ['pmh', 'Experience'],
  k3: ['pmh', '약물 복용력'],
  k4: ['pmh', '약물 복용력'],
  k5: ['pmh', '약물 복용력'],
  k6: ['pmh', '약물 복용력'],
  k7: ['pmh', '약물 복용력'],
  k8: ['pmh', '약물 복용력'],
  k9: ['pmh', '약물 복용력'],
  k10: ['pmh', '약물 복용력'],
  k11: ['pmh', '약물 복용력'],
  k12: ['pmh', '약물 복용력'],
  k13: ['pmh', '약물 복용력'],
  k14: ['pmh', '약물 복용력'],
  k15: ['pmh', '약물 복용력'],
  k16: ['pmh', '약물 복용력'],
  k17: ['pmh', '약물 복용력'],
  k18: ['pmh', '약물 복용력'],
  k19: ['pmh', '약물 복용력'],
  l3: ['pmh', '수술/입원력'],
  l4: ['pmh', '수술/입원력'],
  l5: ['pmh', '수술/입원력'],
  l6: ['pmh', '수술/입원력'],
  l7: ['pmh', '수술/입원력'],
  m3: ['pmh', '건강검진'],
  m4: ['pmh', '건강검진'],
  m5: ['pmh', '건강검진'],
  m6: ['pmh', '건강검진'],
  m7: ['pmh', '건강검진'],
  m8: ['pmh', '건강검진'],
  m9: ['pmh', '건강검진'],
  m10: ['pmh', '건강검진'],
  m11: ['pmh', '건강검진'],
  m12: ['pmh', '건강검진'],
  n3: ['fh', '가족력'],
  n4: ['fh', '가족력'],
  n5: ['fh', '가족력'],
  n6: ['fh', '가족력'],
  n7: ['fh', '가족력'],
  n8: ['fh', '가족력'],
};
