/**
 * dict[0]: 대분류
 * dict[1]: 중분류
 */

export const category = {
  a3: '복통',
  a4: '소화불량',
  a5: '구토',
  a6: '변비',
  a7: '설사',
  a8: '황달',
  a9: '토혈',
  b3: '좌상복부',
  b4: '좌중복부',
  b5: '좌하복부',
  b6: '중상복부',
  b7: '중중복부',
  b8: '중하복부',
  b9: '우상복부',
  b10: '우중복부',
  b11: '우하복부',
  b12: '좌옆구리',
  b13: '우옆구리',
  c3: '느낌',
  c16: '통증',
  c18: '기타',
  d3: '쥐어짜는 듯함',
  d5: '칼로 찌르듯',
  d6: '화끈거림',
  d7: '찢어질듯함',
  d8: '뒤틀리는듯함',
  d9: '묵직함',
  d10: '뭉치는 느낌',
  d11: '더부룩한 느낌',
  d12: '욱씬거리는 느낌',
  d13: '메스꺼운 느낌',
  d14: '속쓰림',
  d15: '가스찬기분',
  d16: 'VAS(통증 10점 만점에 몇점?)',
  d17: '방사통',
  d18: '소화불량',
  d19: '거품',
  d20: '기침',
  d21: '음식물 섞여나옴',
  d22: '담즙 섞여나옴',
  d23: '구토',
  d24: '답답함',
  d25: '분출성(=뿜어져나오는 듯함)',
  d26: '양',
  d27: '색',
  d28: '(변볼때)힘주기',
  d29: '잔변감',
  d30: '항문 막힌 느낌',
  d31: '(변볼때)굵기',
  d32: '(변볼때)복압',
  d33: '(변볼때)굳기',
  d34: '항문 통증',
  d35: '(변볼때)손가락으로 변 긁어내기',
  d37: '냄새',
  d38: '배변횟수',
  d39: '수양성 설사',
  d41: '몸살 증상',
  d42: '입마름',
  d43: '항문에서 고름이 나옴',
  d44: '복부덩어리',
  d46: '소리남',
  e3: '식사 전후 통증 변화',
  e4: '자세에 따른 통증 변화',
  e5: '음식물',
  e6: '다이어트',
  e7: '기침시 통증',
  e8: '음주',
  e9: '약물',
  e10: '무리한 운동',
  e11: '피로',
  e12: '여행력',
  e13: '성관계',
  e14: '배변에 따른 변화',
  e15: '스트레스',
  e16: '주위 사람의 비슷한 증상 유무',
  e17: '대변 습관',
  e18: '기호식품',
  e19: '예민한 성격',
  e20: '귤, 당근 과다 섭취',
  e21: '민물고기 식이',
  e22: '감염력',
  e23: '벌레물린적 유무',
  e24: '복부수술',
  e25: '외상',
  e26: '질세척(질세정제)',
  e27: '차가운 음식',
  e28: '수면',
  f3: '체중변화(증가)',
  f4: '체중변화(유지)',
  f5: '체중변화(감소)',
  f6: '발열',
  f7: '오한',
  f8: '어지러움(=현훈)',
  f9: '옆구리 통증',
  f10: '식욕부진',
  f11: '오심(=구역)',
  f12: '구토',
  f13: '변비',
  f14: '설사',
  f15: '회색변',
  f16: '지방변',
  f17: '혈변',
  f18: '흑색변',
  f19: '빈뇨',
  f20: '절박뇨(화장실 못참음)',
  f21: '야간뇨',
  f22: '배뇨통',
  f23: '혈뇨',
  f24: '소변색변화',
  f25: '질출혈',
  f26: '태동',
  f27: '복부 팽만감',
  f28: '식은땀',
  f29: '황달',
  f30: '신물올라옴',
  f31: '속부글거림',
  f32: '연하곤란(음식 안넘어감)',
  f33: '우울',
  f34: '불안',
  f35: '추위불내성(추위못참음)',
  f36: '더위불내성(더위못참음)',
  f37: '호흡곤란',
  f38: '멍이 잘 듦',
  f39: '코피',
  f40: '시야 이상',
  f41: '근력 저하',
  f42: '보행 이상',
  f43: '목마름',
  f44: '피부건조',
  f45: '지혈장애',
  f46: '관절통',
  f47: '부종',
  f48: '조기포만감',
  f49: '식후불편감',
  f50: '입/항문 궤양',
  f51: '점액질 변',
  f52: '하복부 통증',
  f53: '배변습관 변화',
  f54: '뒤무직',
  f55: '항문통증/항문덩이',
  f56: '전신 출혈 경향',
  f57: '경부 강직',
  f58: '이명(귀에 소리 윙윙거림)',
  f59: '청각저하',
  f60: '두통',
  g3: '증상/통증 추이',
  g8: '주기',
  h3: '점점 악화됨',
  h4: '일정함',
  h5: '점점 호전됨',
  h6: '호전과 악화의 반복',
  h8: '간헐적',
  h9: '지속적',
  i3: '처음',
  i4: '과거에 있음',
  j3: '당뇨',
  j4: '결핵',
  j5: '고혈압',
  j6: '간염',
  j7: '위궤양',
  j8: '요로결석',
  j9: '소화기질환',
  j10: '부인과질환',
  j11: '암',
  j12: '고지혈증',
  j13: '치질',
  j14: '치루',
  j15: '신우신염',
  j16: '염증성 장질환',
  j17: '궤양',
  j18: '과민성 장증후군',
  j19: '정신질환력',
  j20: '약복용력없음',
  j21: '위염',
  j22: '두통',
  j23: '장염',
  k3: '소화제',
  k4: '제산제',
  k5: '진통소염제',
  k6: '칼슘제제',
  k7: '엽산제',
  k8: '철분제',
  k9: '혈압약',
  k10: '관절염약',
  k11: '당뇨약',
  k12: '고지혈증약',
  k13: '혈압약',
  k14: '제산제',
  k15: '변비약',
  k16: '종합비타민',
  k17: '감기약',
  k18: '피임약',
  k19: '항생제',
  l3: '특이사항 없음',
  l4: '수술',
  l5: '입원',
  l6: '척추손상력',
  l7: '방사선 조사력',
  m3: '특이사항 없음',
  m4: '만성위염',
  m5: '고콜레스테롤혈증',
  m6: '결석',
  m7: '산부인과 검진',
  m8: '소화기질환',
  m9: '부인과질환',
  m10: '암',
  m11: '내시경',
  m12: '예방접종',
  n3: '특이사항 없음',
  n4: '어머니',
  n5: '아버지',
  n6: '자매',
  n7: '형제',
  n8: '조부모(할아버지, 할머니)',
  o3: '스트레스',
  o4: '직업',
  o5: '음주',
  o6: '흡연',
  o7: '커피',
  o8: '식습관',
};

export default {
  a3: ['cc', 'Chief Complaint'],
  a4: ['cc', 'Chief Complaint'],
  a5: ['cc', 'Chief Complaint'],
  a6: ['cc', 'Chief Complaint'],
  a7: ['cc', 'Chief Complaint'],
  a8: ['cc', 'Chief Complaint'],
  a9: ['cc', 'Chief Complaint'],
  b3: ['pi', 'Location'],
  b4: ['pi', 'Location'],
  b5: ['pi', 'Location'],
  b6: ['pi', 'Location'],
  b7: ['pi', 'Location'],
  b8: ['pi', 'Location'],
  b9: ['pi', 'Location'],
  b10: ['pi', 'Location'],
  b11: ['pi', 'Location'],
  b12: ['pi', 'Location'],
  b13: ['pi', 'Location'],
  d3: ['pi', 'Character'],
  d5: ['pi', 'Character'],
  d6: ['pi', 'Character'],
  d7: ['pi', 'Character'],
  d8: ['pi', 'Character'],
  d9: ['pi', 'Character'],
  d10: ['pi', 'Character'],
  d11: ['pi', 'Character'],
  d12: ['pi', 'Character'],
  d13: ['pi', 'Character'],
  d14: ['pi', 'Character'],
  d15: ['pi', 'Character'],
  d16: ['pi', 'Character'],
  d17: ['pi', 'Character'],
  d18: ['pi', 'Character'],
  d19: ['pi', 'Character'],
  d20: ['pi', 'Character'],
  d21: ['pi', 'Character'],
  d22: ['pi', 'Character'],
  d23: ['pi', 'Character'],
  d24: ['pi', 'Character'],
  d25: ['pi', 'Character'],
  d26: ['pi', 'Character'],
  d27: ['pi', 'Character'],
  d28: ['pi', 'Character'],
  d29: ['pi', 'Character'],
  d30: ['pi', 'Character'],
  d31: ['pi', 'Character'],
  d32: ['pi', 'Character'],
  d33: ['pi', 'Character'],
  d34: ['pi', 'Character'],
  d35: ['pi', 'Character'],
  d37: ['pi', 'Character'],
  d38: ['pi', 'Character'],
  d39: ['pi', 'Character'],
  d41: ['pi', 'Character'],
  d42: ['pi', 'Character'],
  d43: ['pi', 'Character'],
  d44: ['pi', 'Character'],
  d46: ['pi', 'Character'],
  e3: ['pi', 'Factors'],
  e4: ['pi', 'Factors'],
  e5: ['pi', 'Factors'],
  e6: ['pi', 'Factors'],
  e7: ['pi', 'Factors'],
  e8: ['pi', 'Factors'],
  e9: ['pi', 'Factors'],
  e10: ['pi', 'Factors'],
  e11: ['pi', 'Factors'],
  e12: ['pi', 'Factors'],
  e13: ['pi', 'Factors'],
  e14: ['pi', 'Factors'],
  e15: ['pi', 'Factors'],
  e16: ['pi', 'Factors'],
  e17: ['pi', 'Factors'],
  e18: ['pi', 'Factors'],
  e19: ['pi', 'Factors'],
  e20: ['pi', 'Factors'],
  e21: ['pi', 'Factors'],
  e22: ['pi', 'Factors'],
  e23: ['pi', 'Factors'],
  e24: ['pi', 'Factors'],
  e25: ['pi', 'Factors'],
  e26: ['pi', 'Factors'],
  e27: ['pi', 'Factors'],
  e28: ['pi', 'Factors'],
  f3: ['ros', 'Associated Symptoms'],
  f4: ['ros', 'Associated Symptoms'],
  f5: ['ros', 'Associated Symptoms'],
  f6: ['ros', 'Associated Symptoms'],
  f7: ['ros', 'Associated Symptoms'],
  f8: ['ros', 'Associated Symptoms'],
  f9: ['ros', 'Associated Symptoms'],
  f10: ['ros', 'Associated Symptoms'],
  f11: ['ros', 'Associated Symptoms'],
  f12: ['ros', 'Associated Symptoms'],
  f13: ['ros', 'Associated Symptoms'],
  f14: ['ros', 'Associated Symptoms'],
  f15: ['ros', 'Associated Symptoms'],
  f16: ['ros', 'Associated Symptoms'],
  f17: ['ros', 'Associated Symptoms'],
  f18: ['ros', 'Associated Symptoms'],
  f19: ['ros', 'Associated Symptoms'],
  f20: ['ros', 'Associated Symptoms'],
  f21: ['ros', 'Associated Symptoms'],
  f22: ['ros', 'Associated Symptoms'],
  f23: ['ros', 'Associated Symptoms'],
  f24: ['ros', 'Associated Symptoms'],
  f25: ['ros', 'Associated Symptoms'],
  f26: ['ros', 'Associated Symptoms'],
  f27: ['ros', 'Associated Symptoms'],
  f28: ['ros', 'Associated Symptoms'],
  f29: ['ros', 'Associated Symptoms'],
  f30: ['ros', 'Associated Symptoms'],
  f31: ['ros', 'Associated Symptoms'],
  f32: ['ros', 'Associated Symptoms'],
  f33: ['ros', 'Associated Symptoms'],
  f34: ['ros', 'Associated Symptoms'],
  f35: ['ros', 'Associated Symptoms'],
  f36: ['ros', 'Associated Symptoms'],
  f37: ['ros', 'Associated Symptoms'],
  f38: ['ros', 'Associated Symptoms'],
  f39: ['ros', 'Associated Symptoms'],
  f40: ['ros', 'Associated Symptoms'],
  f41: ['ros', 'Associated Symptoms'],
  f42: ['ros', 'Associated Symptoms'],
  f43: ['ros', 'Associated Symptoms'],
  f44: ['ros', 'Associated Symptoms'],
  f45: ['ros', 'Associated Symptoms'],
  f46: ['ros', 'Associated Symptoms'],
  f47: ['ros', 'Associated Symptoms'],
  f48: ['ros', 'Associated Symptoms'],
  f49: ['ros', 'Associated Symptoms'],
  f50: ['ros', 'Associated Symptoms'],
  f51: ['ros', 'Associated Symptoms'],
  f52: ['ros', 'Associated Symptoms'],
  f53: ['ros', 'Associated Symptoms'],
  f54: ['ros', 'Associated Symptoms'],
  f55: ['ros', 'Associated Symptoms'],
  f56: ['ros', 'Associated Symptoms'],
  f57: ['ros', 'Associated Symptoms'],
  f58: ['ros', 'Associated Symptoms'],
  f59: ['ros', 'Associated Symptoms'],
  f60: ['ros', 'Associated Symptoms'],
  g3: ['pi', 'Course'],
  g8: ['pi', 'Course'],
  h3: ['pi', 'Course'],
  h6: ['pi', 'Course'],
  h8: ['pi', 'Course'],
  j3: ['pmh', 'Experience'],
  j4: ['pmh', 'Experience'],
  j5: ['pmh', 'Experience'],
  j6: ['pmh', 'Experience'],
  j7: ['pmh', 'Experience'],
  j8: ['pmh', 'Experience'],
  j9: ['pmh', 'Experience'],
  j10: ['pmh', 'Experience'],
  j11: ['pmh', 'Experience'],
  j12: ['pmh', 'Experience'],
  j13: ['pmh', 'Experience'],
  j14: ['pmh', 'Experience'],
  j15: ['pmh', 'Experience'],
  j16: ['pmh', 'Experience'],
  j17: ['pmh', 'Experience'],
  j18: ['pmh', 'Experience'],
  j19: ['pmh', 'Experience'],
  j20: ['pmh', 'Experience'],
  j21: ['pmh', 'Experience'],
  j22: ['pmh', 'Experience'],
  j23: ['pmh', 'Experience'],
  k3: ['pmh', '약물 복용력'],
  k4: ['pmh', '약물 복용력'],
  k5: ['pmh', '약물 복용력'],
  k6: ['pmh', '약물 복용력'],
  k7: ['pmh', '약물 복용력'],
  k8: ['pmh', '약물 복용력'],
  k9: ['pmh', '약물 복용력'],
  k10: ['pmh', '약물 복용력'],
  k11: ['pmh', '약물 복용력'],
  k12: ['pmh', '약물 복용력'],
  k13: ['pmh', '약물 복용력'],
  k14: ['pmh', '약물 복용력'],
  k15: ['pmh', '약물 복용력'],
  k16: ['pmh', '약물 복용력'],
  k17: ['pmh', '약물 복용력'],
  k18: ['pmh', '약물 복용력'],
  k19: ['pmh', '약물 복용력'],
  l3: ['pmh', '수술/입원력'],
  l4: ['pmh', '수술/입원력'],
  l5: ['pmh', '수술/입원력'],
  l6: ['pmh', '수술/입원력'],
  l7: ['pmh', '수술/입원력'],
  m3: ['pmh', '건강검진'],
  m4: ['pmh', '건강검진'],
  m5: ['pmh', '건강검진'],
  m6: ['pmh', '건강검진'],
  m7: ['pmh', '건강검진'],
  m8: ['pmh', '건강검진'],
  m9: ['pmh', '건강검진'],
  m10: ['pmh', '건강검진'],
  m11: ['pmh', '건강검진'],
  m12: ['pmh', '건강검진'],
  n3: ['fh', '가족력'],
  n4: ['fh', '가족력'],
  n5: ['fh', '가족력'],
  n6: ['fh', '가족력'],
  n7: ['fh', '가족력'],
  n8: ['fh', '가족력'],
};
